<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="store.aspx.cs" Inherits="網頁設計.store" %>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
</head>
<body>
    <form id="form1" runat="server">
    <div>
    
        <h1>
            <asp:Label ID="Label1" runat="server" Text="Label"></asp:Label>
        </h1>
    
    </div>
    <h3>
        <asp:DropDownList ID="DropDownList1" runat="server" AutoPostBack="True" 
            DataSourceID="SqlDataSource1" DataTextField="drink_name" 
            DataValueField="drink_price" 
            onselectedindexchanged="DropDownList1_SelectedIndexChanged">
            <asp:ListItem></asp:ListItem>
        </asp:DropDownList>
        <asp:Label ID="Label2" runat="server" Text="Labe2"></asp:Label>
    <asp:Button ID="Button1" runat="server" onclick="Button1_Click" Text="開始下單" />
    </h3>
    <asp:DropDownList ID="numDropDownList" runat="server" Visible="False">
        <asp:ListItem Value="1"></asp:ListItem>
        <asp:ListItem Value="2"></asp:ListItem>
        <asp:ListItem Value="3"></asp:ListItem>
        <asp:ListItem Value="4"></asp:ListItem>
        <asp:ListItem Value="5"></asp:ListItem>
        <asp:ListItem Value="6"></asp:ListItem>
        <asp:ListItem Value="7"></asp:ListItem>
        <asp:ListItem Value="8"></asp:ListItem>
        <asp:ListItem Value="9"></asp:ListItem>
        <asp:ListItem Value="10"></asp:ListItem>
    </asp:DropDownList>
    <asp:Label ID="Label3" runat="server" Text="杯" Visible="False"></asp:Label>
    <asp:DropDownList ID="sweetDropDownList" runat="server" Visible="False">
        <asp:ListItem>正常</asp:ListItem>
        <asp:ListItem>半糖</asp:ListItem>
        <asp:ListItem>微糖</asp:ListItem>
    </asp:DropDownList>
    <asp:DropDownList ID="iceDropDownList" runat="server" Visible="False">
        <asp:ListItem>正常</asp:ListItem>
        <asp:ListItem>半冰</asp:ListItem>
        <asp:ListItem>少冰</asp:ListItem>
        <asp:ListItem>去冰</asp:ListItem>
    </asp:DropDownList>
    <asp:Button ID="Button2" runat="server" onclick="Button2_Click" Text="增加品項" 
        Visible="False" />
    <asp:SqlDataSource ID="SqlDataSource1" runat="server" 
        ConnectionString="<%$ ConnectionStrings:ConnectionString %>" 
        SelectCommand="SELECT [drink_name], [drink_price] FROM [drink]" 
        
        InsertCommand="INSERT INTO [order] (order_time, order_user_phone) VALUES (GETDATE(), @order_user_phone)" 
        UpdateCommand="UPDATE user1 SET user_money = @money WHERE (user_name = @name)">
        <InsertParameters>
            <asp:SessionParameter Name="order_user_phone" SessionField="user_phone" />
        </InsertParameters>
        <UpdateParameters>
            <asp:SessionParameter Name="money" SessionField="user_money" />
            <asp:SessionParameter Name="name" SessionField="user_name" />
        </UpdateParameters>
    </asp:SqlDataSource>
    <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" 
        DataSourceID="SqlDataSource2" Visible="False" 
        AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" 
        DataKeyNames="id_order_item,id_order" onrowdatabound="GridView1_RowDataBound" 
        onrowdeleted="GridView1_RowDeleted">
        <Columns>
            <asp:TemplateField HeaderText="飲品" SortExpression="drink_name">
                <EditItemTemplate>
                    <asp:Label ID="Label6" runat="server" Text='<%# Bind("drink_name") %>'></asp:Label>
                    <asp:DropDownList ID="DropDownList2" runat="server" 
                        DataSourceID="SqlDataSource3" DataTextField="name" DataValueField="id_drink" 
                        SelectedValue='<%# Bind("id_drink") %>'>
                    </asp:DropDownList>
                    <asp:SqlDataSource ID="SqlDataSource3" runat="server" 
                        ConnectionString="<%$ ConnectionStrings:ConnectionString %>" 
                        SelectCommand="SELECT [id_drink], rtrim([drink_name]) as name FROM [drink]">
                    </asp:SqlDataSource>
                </EditItemTemplate>
                <ItemTemplate>
                    <asp:Label ID="Label1" runat="server" Text='<%# Bind("drink_name") %>'></asp:Label>
                </ItemTemplate>
            </asp:TemplateField>
            <asp:TemplateField HeaderText="數量" SortExpression="num">
                <EditItemTemplate>
                    <asp:Label ID="Label2" runat="server" Text='<%# Bind("num") %>'></asp:Label>
                    <asp:DropDownList ID="DropDownList5" runat="server" 
                        SelectedValue='<%# Bind("num") %>'>
                        <asp:ListItem Value="1"></asp:ListItem>
                        <asp:ListItem Value="2"></asp:ListItem>
                        <asp:ListItem Value="3"></asp:ListItem>
                        <asp:ListItem Value="4"></asp:ListItem>
                        <asp:ListItem Value="5"></asp:ListItem>
                        <asp:ListItem Value="6"></asp:ListItem>
                        <asp:ListItem Value="7"></asp:ListItem>
                        <asp:ListItem Value="8"></asp:ListItem>
                        <asp:ListItem Value="9"></asp:ListItem>
                        <asp:ListItem Value="10"></asp:ListItem>
                    </asp:DropDownList>
                </EditItemTemplate>
                <ItemTemplate>
                    <asp:Label ID="Label2" runat="server" Text='<%# Bind("num") %>'></asp:Label>
                </ItemTemplate>
            </asp:TemplateField>
            <asp:TemplateField HeaderText="甜度" SortExpression="sweet">
                <EditItemTemplate>
                    <asp:Label ID="Label7" runat="server" Text='<%# Bind("sweet") %>'></asp:Label>
                    <asp:DropDownList ID="DropDownList3" runat="server" 
                        SelectedValue='<%# Bind("sweet") %>'>
                        <asp:ListItem>正常</asp:ListItem>
                        <asp:ListItem>半糖</asp:ListItem>
                        <asp:ListItem>微糖</asp:ListItem>
                    </asp:DropDownList>
                </EditItemTemplate>
                <ItemTemplate>
                    <asp:Label ID="Label3" runat="server" Text='<%# Bind("sweet") %>'></asp:Label>
                </ItemTemplate>
            </asp:TemplateField>
            <asp:TemplateField HeaderText="冰塊" SortExpression="ice">
                <EditItemTemplate>
                    <asp:Label ID="Label8" runat="server" Text='<%# Bind("ice") %>'></asp:Label>
                    <asp:DropDownList ID="DropDownList4" runat="server" 
                        SelectedValue='<%# Bind("ice") %>'>
                        <asp:ListItem>正常</asp:ListItem>
                        <asp:ListItem>半冰</asp:ListItem>
                        <asp:ListItem>少冰</asp:ListItem>
                        <asp:ListItem>去冰</asp:ListItem>
                    </asp:DropDownList>
                </EditItemTemplate>
                <ItemTemplate>
                    <asp:Label ID="Label4" runat="server" Text='<%# Bind("ice") %>'></asp:Label>
                </ItemTemplate>
            </asp:TemplateField>
            <asp:TemplateField HeaderText="小計" SortExpression="total">
                <EditItemTemplate>
                    <asp:Label ID="Label5" runat="server" Text='<%# Eval("total") %>'></asp:Label>
                </EditItemTemplate>
                <ItemTemplate>
                    <asp:Label ID="Label5" runat="server" Text='<%# Bind("total") %>'></asp:Label>
                </ItemTemplate>
            </asp:TemplateField>
        </Columns>
    </asp:GridView>
    <asp:SqlDataSource ID="SqlDataSource2" runat="server" 
        ConnectionString="<%$ ConnectionStrings:ConnectionString %>" 
        InsertCommand="INSERT INTO order_item(id_order, id_drink, num, sweet, ice) VALUES (@id_order, @id_drink, @num, @sweet, @ice)" 
        
        SelectCommand="SELECT order_item.id_order, drink.drink_name, order_item.num, order_item.sweet, order_item.ice, order_item.num * drink.drink_price AS total, drink.id_drink, order_item.id_order_item FROM order_item INNER JOIN drink ON order_item.id_drink = drink.id_drink WHERE (order_item.id_order = @id_order)" 
        DeleteCommand="DELETE FROM order_item WHERE (id_order_item = @id_order_item)" 
        UpdateCommand="UPDATE order_item SET id_drink =@id_drink, num=@num, sweet = @sweet, ice = @ice WHERE (id_order_item=@id_order_item)">
        <DeleteParameters>
            <asp:ControlParameter ControlID="GridView1" Name="id_order_item" 
                PropertyName="SelectedDataKey" />
        </DeleteParameters>
        <InsertParameters>
            <asp:SessionParameter Name="id_order" SessionField="id_order" />
            <asp:ControlParameter ControlID="DropDownList1" Name="id_drink" 
                PropertyName="SelectedIndex" Type="String" />
            <asp:ControlParameter ControlID="numDropDownList" Name="num" 
                PropertyName="SelectedValue" />
            <asp:ControlParameter ControlID="sweetDropDownList" Name="sweet" 
                PropertyName="SelectedValue" />
            <asp:ControlParameter ControlID="iceDropDownList" Name="ice" 
                PropertyName="SelectedValue" />
        </InsertParameters>
        <SelectParameters>
            <asp:SessionParameter Name="id_order" SessionField="id_order" />
        </SelectParameters>
        <UpdateParameters>
            <asp:ControlParameter ControlID="GridView1" Name="id_drink" 
                PropertyName="SelectedValue" />
            <asp:ControlParameter ControlID="GridView1" Name="num" 
                PropertyName="SelectedValue" />
            <asp:ControlParameter ControlID="GridView1" Name="sweet" 
                PropertyName="SelectedValue" />
            <asp:ControlParameter ControlID="GridView1" Name="ice" 
                PropertyName="SelectedValue" />
            <asp:ControlParameter ControlID="GridView1" Name="id_order_item" 
                PropertyName="SelectedDataKey" />
        </UpdateParameters>
    </asp:SqlDataSource>
    <asp:Label ID="totalPrice" runat="server" Text="Total Price : 0$" 
        Visible="False"></asp:Label>
    <asp:Button ID="check" runat="server" onclick="check_Click" Text="確定訂單" 
        Visible="False" />
    <asp:Button ID="cancel" runat="server" onclick="cancel_Click" Text="取消訂單" 
        Visible="False" />
    <asp:SqlDataSource ID="SqlDataSource4" runat="server" 
        ConnectionString="<%$ ConnectionStrings:ConnectionString %>" 
        DeleteCommand="DELETE FROM order_item WHERE (id_order = @id_order)" 
        SelectCommand="SELECT * FROM [order_item]">
        <DeleteParameters>
            <asp:SessionParameter Name="id_order" SessionField="id_order" />
        </DeleteParameters>
    </asp:SqlDataSource>
    <h4>
        <asp:Label ID="error" runat="server" Text="儲值金不足，請修改或取消訂單" Visible="False"></asp:Label>
        <asp:GridView ID="GridView2" runat="server" AutoGenerateColumns="False" 
            DataSourceID="checkqt" Visible="False">
            <Columns>
                <asp:TemplateField HeaderText="id_drink" SortExpression="id_drink">
                    <EditItemTemplate>
                        <asp:Label ID="Label1" runat="server" Text="Label"></asp:Label>
                    </EditItemTemplate>
                    <ItemTemplate>
                        <asp:Label ID="Label1" runat="server" Text='<%# Bind("id_drink") %>'></asp:Label>
                    </ItemTemplate>
                </asp:TemplateField>
                <asp:TemplateField HeaderText="num" SortExpression="num">
                    <EditItemTemplate>
                        <asp:Label ID="Label2" runat="server" Text='<%# Eval("num") %>'></asp:Label>
                    </EditItemTemplate>
                    <ItemTemplate>
                        <asp:Label ID="Label2" runat="server" Text='<%# Bind("num") %>'></asp:Label>
                    </ItemTemplate>
                </asp:TemplateField>
            </Columns>
        </asp:GridView>
        <asp:SqlDataSource ID="checkqt" runat="server" 
            ConnectionString="<%$ ConnectionStrings:ConnectionString %>" 
            SelectCommand="SELECT id_drink, SUM(num) AS num FROM order_item WHERE (id_order = @id_order) GROUP BY id_drink" 
            UpdateCommand="UPDATE drink SET drink_qt = @qt WHERE (id_drink = @id_drink)">
            <SelectParameters>
                <asp:SessionParameter Name="id_order" SessionField="id_order" />
            </SelectParameters>
            <UpdateParameters>
                <asp:SessionParameter Name="qt" SessionField="qt" />
                <asp:SessionParameter Name="id_drink" SessionField="id_drink" />
            </UpdateParameters>
        </asp:SqlDataSource>
        <asp:GridView ID="qtview" runat="server" AutoGenerateColumns="False" 
            DataSourceID="SqlDataSource5" Visible="False">
            <Columns>
                <asp:TemplateField HeaderText="id_drink" InsertVisible="False" 
                    SortExpression="id_drink">
                    <EditItemTemplate>
                        <asp:Label ID="Label1" runat="server" Text='<%# Eval("id_drink") %>'></asp:Label>
                    </EditItemTemplate>
                    <ItemTemplate>
                        <asp:Label ID="Label1" runat="server" Text='<%# Bind("id_drink") %>'></asp:Label>
                    </ItemTemplate>
                </asp:TemplateField>
                <asp:TemplateField HeaderText="drink_qt" SortExpression="drink_qt">
                    <EditItemTemplate>
                        <asp:Label ID="Label2" runat="server" Text="Label"></asp:Label>
                    </EditItemTemplate>
                    <ItemTemplate>
                        <asp:Label ID="Label2" runat="server" Text='<%# Bind("drink_qt") %>'></asp:Label>
                    </ItemTemplate>
                </asp:TemplateField>
            </Columns>
        </asp:GridView>
        <asp:SqlDataSource ID="SqlDataSource5" runat="server" 
            ConnectionString="<%$ ConnectionStrings:ConnectionString %>" 
            SelectCommand="SELECT [id_drink], [drink_qt] FROM [drink]">
        </asp:SqlDataSource>
        <asp:Label ID="notenough" runat="server" Text="庫存不足" Visible="False"></asp:Label>
    </h4>
    <h3>
        <asp:Image ID="Image1" runat="server" />
    </h3>
    <p>
        &nbsp;</p>
    </form>
</body>
</html>
